version: "3"
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=cowpoke
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    # This builds the cowpoke:web container
    image: cowpoke:web
    depends_on:
      - db
    links:
      - db
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY
